In [1]:
#Задание 1

#Создайте numpy array с элементами от числа N до 0.

In [2]:
import numpy as np

In [4]:
array_np = np.arange(8)
array_np_rev = array_np[::-1]
print(array_np_rev)

[7 6 5 4 3 2 1 0]


In [5]:
#Задание 2

#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [38]:
diag = np.diag(np.arange(50, 0, -5), k = 0)

summ = 0
for line in diag:
    for d in line:
        summ += d
        
print(diag)        
print(summ)

[[50  0  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0  0]
 [ 0  0 40  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  5]]
275


In [8]:
#Задание 3

#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [9]:
from numpy import linalg

In [10]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [12]:
#Задание 4

#Имеется матрица покупок в интернет-магазине. 
#Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

#Найдите самого похожего пользователя. 
#Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [13]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [14]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [56]:
def cosine(users_stats, next_user_stats):
   
    users_stats_Length = np.linalg.norm(users_stats)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / (users_stats_Length * next_user_stats_Length)

cosine(users_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

In [74]:
rows = np.array([cosine(row, next_user_stats) for row in users_stats])
similar_user = np.argmax(rows)

print(similar_user)

7
